import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { verifyUser } from "@/utils/verifyToken";
import { IUserData } from "@/utils/dtos";
export const metadata: Metadata = {
  title: "cloud hosting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get("authToken")?.value as string;
  const verify = verifyUser(token);
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar UserData={verify as IUserData}></Navbar>
        {children}
        <Footer></Footer>
        <Toaster />
      </body>
    </html>
  );
}
