import React from "react";
import AdminSideBar from "./adminSideBar";
import { Metadata } from "next";
type AdminSidePage = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};
const AdminLayoutPage = ({ children }: AdminSidePage) => {
  return (
    <div className="flex items-start h-[80vh] overflow-hidden">
      <div className="w-16 lg:w-1/5 h-full bg-gray-800 p-4 ">
        <AdminSideBar></AdminSideBar>
      </div>
      <div className="w-full p-4">{children}</div>
    </div>
  );
};

export default AdminLayoutPage;
