import { searchArticles } from "@/app/apiCalls/articleApis";
import ArticleItem from "@/components/articles/articleItem";
import { Article } from "@prisma/client";
import { Metadata } from "next";
import React from "react";

type Iprops = {
  params: object;
  searchParams: { search: string };
};

export const metadata: Metadata = {
  title: "Search Article || Search",
  description: "Generated by create next app",
};
const SearchArticle = async (props: Iprops) => {
  const search: Article[] = await searchArticles(props?.searchParams?.search);
  return (
    <div className="p-4 container mx-auto">
      <h1 className=" font-semibold text-4xl my-5 px-2">Search Article</h1>
      <div>
        <div className=" grid place-items-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {search.length > 0 ? (
            search?.map((article) => (
              <ArticleItem key={article.id} article={article}></ArticleItem>
            ))
          ) : (
            <h1 className="text-3xl m-auto text-center col-span-3 h-96 flex items-center justify-center">
              NO ARTICLES FOUND
            </h1>
          )}
        </div>
      </div>
    </div>
  );
};

export default SearchArticle;
